package ca.meshytama.kotlindeathmonster.keywords

import org.json.JSONArray

/**
 * JSON-parsing keyword model.
 */
class KeywordModelImpl(json: JSONArray) : KeywordModel {

    /**
     * Sadly, we can't just name this "allKeywords" and let the autogenerated getter implement the interface method :(
     */
    val keywords: Collection<Keyword> = KeywordParser.parseJsonArray(json)

    override fun getAllKeywords(): Collection<Keyword> {
        return keywords
    }
}